allowBuilds:
  '@google/genai': true
  '@parcel/watcher': true
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
  protobufjs: true

minimumReleaseAgeExclude:
  - npm-check-updates@23.0.1
  - tsx@4.23.9
  - '@shikijs/core@4.4.2'
  - '@shikijs/engine-javascript@4.4.2'
  - '@shikijs/engine-oniguruma@4.4.2'
  - '@shikijs/langs@4.4.2'
  - '@shikijs/primitive@4.4.2'
  - '@shikijs/themes@4.4.2'
  - '@shikijs/types@4.4.2'
  - shiki@4.4.2
